# Generated by Django 6.0 on 2025-12-15 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userdata_ts_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ts_ins',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
