# Generated by Django 6.0 on 2025-12-15 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdata_ts_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ts_ins',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
